name: Python Application CI/CD

# O pipeline roda sempre que houver um push ou merge nessas duas branches
on:
  push:
    branches:
      - develop
      - main

# Dica do LAB: Uso de variáveis globais para evitar repetição
env:
  IMAGE_NAME: "api-fastapi-app"

jobs:
  # 1. Job de Integração Contínua (Build e Testes)
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Simular Build da Imagem
        run: |
          echo "Construindo a imagem Docker: ${{ env.IMAGE_NAME }}"

  # 2. Job de Deploy em Homologação (Automático)
  deploy_homologacao:
    needs: build_and_test
    # Regra do LAB: Só roda se o push for na branch 'develop'
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy em Homologação via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Conectado na EC2 para Homologação!"
            echo "Subindo a aplicação automaticamente na porta 8080..."
            # O comando real de docker que rodaria aqui na porta 8080 conforme o LAB:
            # docker run -d -p 8080:8000 ${{ env.IMAGE_NAME }}

  # 3. Job de Deploy em Produção (Controlado e com Aprovação Manual)
  deploy_producao:
    needs: build_and_test
    # Regra do LAB: Só roda se o push/merge for na branch 'main'
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    # Vincula ao Environment do GitHub para exigir a aprovação manual
    environment: production
    
    steps:
      - name: Deploy em Produção via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Conectado na EC2 para PRODUÇÃO!"
            echo "Subindo a aplicação no ambiente de produção..."
            # O comando real de docker que rodaria aqui na porta padrão de produção:
            # docker run -d -p 8000:8000 ${{ env.IMAGE_NAME }}
