name: Python Application CI/CD

# O pipeline roda sempre que houver um push ou merge nessas duas branches
on:
  push:
    branches:
      - develop
      - main

# Variável global recomendada para evitar repetição no código
env:
  IMAGE_NAME: "api-fastapi-app"

jobs:
  # 1. Job de Integração Contínua (Build e Testes)
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Simular Build da Imagem
        run: |
          echo "Construindo a imagem Docker: ${{ env.IMAGE_NAME }}"

  # 2. Job de Deploy em Homologação (Automático na branch develop)
  deploy_homologacao:
    needs: build_and_test
    # Regra: Só roda se o push/merge for na branch 'develop'
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Executar Deploy em Homologação via SSH Nativo
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          
          ssh -o StrictHostKeyChecking=no -o ConnectTimeout=15 -i ~/.ssh/id_rsa ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} << 'EOF'
            echo "Conectado com sucesso na EC2 de HOMOLOGAÇÃO!"
            echo "Subindo aplicação na porta 8080..."
            # docker run -d -p 8080:8000 ${{ env.IMAGE_NAME }}
          EOF

  # 3. Job de Deploy em Produção (Controlado e com Aprovação Manual)
  deploy_producao:
    needs: build_and_test
    # Regra do LAB: Garante que produção só ativa na branch main
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    # Vincula ao Environment do GitHub para exigir a aprovação manual
    environment: production
    
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Executar Deploy em Produção via SSH Nativo
        run: |
          # 1. Configura a chave privada temporariamente no ambiente do GitHub
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          
          # 2. Executa a conexão SSH nativa com timeout estendido e ignorando checagem estrita de chaves
          ssh -o StrictHostKeyChecking=no -o ConnectTimeout=15 -i ~/.ssh/id_rsa ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} << 'EOF'
            echo "Conectado com sucesso na EC2 de PRODUÇÃO!"
            echo "Listando containers ativos na máquina:"
            docker ps
            # Seus comandos futuros de deploy em produção entram aqui
          EOF
